### ISSUE TITLE
Wrong link in readme

### ISSUE THREAD

**Issue by charlesbodman** [downplay/downstyle#1]
Just noticed the **Downright** link is a 404 on the readme

https://github.com/downplay/downwrite

👍 

see ya around Discord

**Comment by randomdevpete** [comment]
Oh, thanks I missed that!

**Comment by randomdevpete** [comment]
Fixed in https://github.com/downplay/downstyle/commit/918b4ceebf6e65b31517c34140884a57125cd7d1
